"""Compatibility imports for the package name used before RIMKit 0.2."""

from rimkit import (
    CollisionPassDiagnostics,
    DiagnosticTrajectoriesResult,
    DmrProgress,
    DmrResult,
    FinalCollisionDiagnostics,
    FinalCollisionProgress,
    FinalCollisionResult,
    FpaIkResult,
    FpaResult,
    FpaSolveRecord,
    FpaTargetsResult,
    InitialCollisionDiagnostics,
    InitialCollisionProgress,
    InitialCollisionResult,
    PreflightResult,
    Retargeter,
    RetargetRunResult,
    ReviewRunResult,
    RunConfig,
    TargetTrajectoriesResult,
    __version__,
    get_robot,
    list_robots,
    run_review,
)

__all__ = [
    "CollisionPassDiagnostics",
    "DiagnosticTrajectoriesResult",
    "DmrProgress",
    "DmrResult",
    "FinalCollisionDiagnostics",
    "FinalCollisionProgress",
    "FinalCollisionResult",
    "FpaIkResult",
    "FpaResult",
    "FpaSolveRecord",
    "FpaTargetsResult",
    "InitialCollisionDiagnostics",
    "InitialCollisionProgress",
    "InitialCollisionResult",
    "PreflightResult",
    "RetargetRunResult",
    "Retargeter",
    "ReviewRunResult",
    "RunConfig",
    "TargetTrajectoriesResult",
    "__version__",
    "get_robot",
    "list_robots",
    "run_review",
]
