"""Canonical registry for the supported robot models."""

from types import MappingProxyType

from core_retarget.exceptions import ConfigurationError
from core_retarget.robots.schema import RobotSpec

_UNITREE_REPOSITORY = "https://github.com/unitreerobotics/unitree_mujoco"
_UNITREE_REVISION = "ae6a8403e272733e9996ef59990880330496177f"
_ROBOTIS_REPOSITORY = "https://github.com/ROBOTIS-GIT/ai_sapiens"
_ROBOTIS_REVISION = "c2880e89fb3451a07b6d2600e274224ffcf912e4"
_MUJOCO_MENAGERIE_REPOSITORY = "https://github.com/google-deepmind/mujoco_menagerie"
_MUJOCO_MENAGERIE_REVISION = "71f066ad0be9cd271f7ed58c030243ef157af9f4"
_LIMX_REPOSITORY = "https://github.com/limxdynamics/humanoid-description"
_LIMX_REVISION = "a90f734c153aa3ecffc8b674af1e0a323cb55d1a"
_GMR_REPOSITORY = "https://github.com/YanjieZe/GMR"
_GMR_REVISION = "39c70d031287d899eade658cea3d88b41402356c"


_ROBOTS = {
    "g1": RobotSpec(
        robot_id="g1",
        display_name="G1 29-DOF",
        manufacturer="Unitree Robotics",
        model_relpath="robots/unitree/g1/g1_29dof.xml",
        scene_relpath="scenes/g1.xml",
        license_spdx="BSD-3-Clause",
        license_relpath="robots/unitree/LICENSE",
        source_repository=_UNITREE_REPOSITORY,
        source_revision=_UNITREE_REVISION,
        source_manifest_relpath="robots/unitree/SOURCE.yaml",
        model_sha256="5bfd3cafff4a1853f0971b17cf19bd564989915cfc40a62f40f2d8c5714f17cb",
        expected_nq=36,
        expected_nv=35,
        expected_nu=29,
        required_bodies=(
            "pelvis",
            "left_hip_roll_link",
            "left_knee_link",
            "left_ankle_roll_link",
            "left_sole_link",
            "left_toe_link",
            "right_hip_roll_link",
            "right_knee_link",
            "right_ankle_roll_link",
            "right_sole_link",
            "right_toe_link",
            "torso_link",
            "left_elbow_link",
            "right_elbow_link",
            "left_finger_link",
            "right_finger_link",
        ),
        required_joints=(
            "floating_base_joint",
            "left_hip_pitch_joint",
            "left_knee_joint",
            "left_ankle_pitch_joint",
            "right_hip_pitch_joint",
            "right_knee_joint",
            "right_ankle_pitch_joint",
        ),
        required_sites=("lsole", "lt", "rsole", "rt", "lh_tip", "rh_tip"),
    ),
    "h1": RobotSpec(
        robot_id="h1",
        display_name="H1",
        manufacturer="Unitree Robotics",
        model_relpath="robots/unitree/h1/h1.xml",
        scene_relpath="scenes/h1.xml",
        license_spdx="BSD-3-Clause",
        license_relpath="robots/unitree/LICENSE",
        source_repository=_UNITREE_REPOSITORY,
        source_revision=_UNITREE_REVISION,
        source_manifest_relpath="robots/unitree/SOURCE.yaml",
        model_sha256="9f01b50a1dc6cc78ff7668f63c88ae2283f7cda73473943509f5d84002479086",
        expected_nq=27,
        expected_nv=26,
        expected_nu=20,
        required_bodies=(
            "pelvis",
            "left_hip_roll_link",
            "left_knee_link",
            "left_ankle_link",
            "left_sole_link",
            "left_toe_link",
            "right_hip_roll_link",
            "right_knee_link",
            "right_ankle_link",
            "right_sole_link",
            "right_toe_link",
            "torso_link",
            "left_hand_tip_link",
            "right_hand_tip_link",
        ),
        required_joints=(
            "left_hip_pitch_joint",
            "left_knee_joint",
            "left_ankle_joint",
            "right_hip_pitch_joint",
            "right_knee_joint",
            "right_ankle_joint",
        ),
        compatibility_joints=("not_use_joint",),
    ),
    "h2": RobotSpec(
        robot_id="h2",
        display_name="H2",
        manufacturer="Unitree Robotics",
        model_relpath="robots/unitree/h2/h2_mujoco.xml",
        scene_relpath="scenes/h2.xml",
        license_spdx="BSD-3-Clause",
        license_relpath="robots/unitree/LICENSE",
        source_repository=_UNITREE_REPOSITORY,
        source_revision=_UNITREE_REVISION,
        source_manifest_relpath="robots/unitree/SOURCE.yaml",
        model_sha256="0c7741f441996f8ed901a723bbe11a995d263be71639e7ddca3eca94fa5f3be0",
        expected_nq=38,
        expected_nv=37,
        expected_nu=31,
        required_bodies=(
            "pelvis",
            "left_hip_roll_link",
            "left_knee_link",
            "left_ankle_pitch_link",
            "left_sole_link",
            "left_toe_link",
            "right_hip_roll_link",
            "right_knee_link",
            "right_ankle_pitch_link",
            "right_sole_link",
            "right_toe_link",
            "torso_link",
            "left_hand_tip_link",
            "right_hand_tip_link",
        ),
        required_joints=(
            "floating_base_joint",
            "left_hip_pitch_joint",
            "left_knee_joint",
            "left_ankle_pitch_joint",
            "right_hip_pitch_joint",
            "right_knee_joint",
            "right_ankle_pitch_joint",
        ),
    ),
    "r1": RobotSpec(
        robot_id="r1",
        display_name="R1",
        manufacturer="Unitree Robotics",
        model_relpath="robots/unitree/r1/R1_C++.xml",
        scene_relpath="scenes/r1.xml",
        license_spdx="BSD-3-Clause",
        license_relpath="robots/unitree/LICENSE",
        source_repository=_UNITREE_REPOSITORY,
        source_revision=_UNITREE_REVISION,
        source_manifest_relpath="robots/unitree/SOURCE.yaml",
        model_sha256="f6a4dea3c222c9336e7a09e72c9a0db103a2c916ef0105447c7dba5fde862d52",
        expected_nq=36,
        expected_nv=35,
        expected_nu=29,
        required_bodies=(
            "pelvis",
            "left_hip_roll_link_aux",
            "left_knee_link_aux",
            "left_ankle_roll_link",
            "left_sole_link",
            "left_toe_link",
            "right_hip_roll_link_aux",
            "right_knee_link_aux",
            "right_ankle_roll_link",
            "right_sole_link",
            "right_toe_link",
            "torso_link",
            "left_hand_tip_link",
            "right_hand_tip_link",
        ),
        required_joints=(
            "floating_base_joint",
            "left_hip_pitch_joint",
            "left_knee_joint",
            "left_ankle_pitch_joint",
            "right_hip_pitch_joint",
            "right_knee_joint",
            "right_ankle_pitch_joint",
        ),
        compatibility_joints=(
            "waist_pitch_joint",
            "left_wrist_pitch_joint",
            "left_wrist_yaw_joint",
            "right_wrist_pitch_joint",
            "right_wrist_yaw_joint",
        ),
    ),
    "k1": RobotSpec(
        robot_id="k1",
        display_name="K1",
        manufacturer="ROBOTIS",
        model_relpath="robots/robotis/k1/k1.xml",
        scene_relpath="scenes/k1.xml",
        license_spdx="Apache-2.0",
        license_relpath="robots/robotis/LICENSE",
        source_repository=_ROBOTIS_REPOSITORY,
        source_revision=_ROBOTIS_REVISION,
        source_manifest_relpath="robots/robotis/SOURCE.yaml",
        model_sha256="bca5845bfb4f3af31687bd4dd34388d6491a43156a84743aa1b83127b1210cea",
        expected_nq=30,
        expected_nv=29,
        expected_nu=23,
        required_bodies=(
            "pelvis",
            "left_hip_roll_link",
            "left_knee_link",
            "left_ankle_roll_link",
            "left_toe_link",
            "right_hip_roll_link",
            "right_knee_link",
            "right_ankle_roll_link",
            "right_toe_link",
            "torso_link",
            "left_wrist",
            "right_wrist",
        ),
        required_joints=(
            "root",
            "left_hip_pitch_joint",
            "left_knee_joint",
            "left_ankle_pitch_joint",
            "right_hip_pitch_joint",
            "right_knee_joint",
            "right_ankle_pitch_joint",
        ),
        required_sites=("base", "lp", "lk", "la", "lt", "rp", "rk", "ra", "rt"),
    ),
    "apollo": RobotSpec(
        robot_id="apollo",
        display_name="Apollo",
        manufacturer="Apptronik",
        model_relpath="robots/apptronik/apollo/apptronik_apollo.xml",
        scene_relpath="scenes/apollo.xml",
        license_spdx="Apache-2.0",
        license_relpath="robots/apptronik/LICENSE",
        source_repository=_MUJOCO_MENAGERIE_REPOSITORY,
        source_revision=_MUJOCO_MENAGERIE_REVISION,
        source_manifest_relpath="robots/apptronik/SOURCE.yaml",
        model_sha256="8954739adbc66b484010af14da7726e57e28965bce7532635bcacd2aad90a2d2",
        expected_nq=39,
        expected_nv=38,
        expected_nu=32,
        required_bodies=(
            "base_link",
            "l_hip_fe_link",
            "l_knee_fe_link_aux",
            "l_foot_link",
            "l_sole_link",
            "l_toe_link",
            "r_hip_fe_link",
            "r_knee_fe_link_aux",
            "r_foot_link",
            "r_sole_link",
            "r_toe_link",
            "torso_link",
            "l_wrist_pitch_link",
            "r_wrist_pitch_link",
        ),
        required_joints=(
            "floating_base",
            "l_hip_fe",
            "l_knee_fe",
            "l_ankle_pd",
            "r_hip_fe",
            "r_knee_fe",
            "r_ankle_pd",
        ),
    ),
    "oli": RobotSpec(
        robot_id="oli",
        display_name="Oli",
        manufacturer="LimX Dynamics",
        model_relpath="robots/limx/oli/xml/HU_D04_01_retarget.xml",
        scene_relpath="scenes/oli.xml",
        license_spdx="Apache-2.0",
        license_relpath="robots/limx/LICENSE",
        source_repository=_LIMX_REPOSITORY,
        source_revision=_LIMX_REVISION,
        source_manifest_relpath="robots/limx/SOURCE.yaml",
        model_sha256="0effc2123090ae9db1980071778946f164d075adb77034651f9e508ad3640b5a",
        expected_nq=68,
        expected_nv=61,
        expected_nu=31,
        required_bodies=(
            "base_link",
            "left_hip_roll_link",
            "left_knee_link",
            "left_ankle_roll_link",
            "contact_foot_center_L",
            "contact_foot_tip_L",
            "right_hip_roll_link",
            "right_knee_link",
            "right_ankle_roll_link",
            "contact_foot_center_R",
            "contact_foot_tip_R",
            "waist_pitch_link",
            "left_hand_manip",
            "right_hand_manip",
        ),
        required_joints=(
            "floating_base_joint",
            "left_hip_pitch_joint",
            "left_knee_joint",
            "left_ankle_pitch_joint",
            "right_hip_pitch_joint",
            "right_knee_joint",
            "right_ankle_pitch_joint",
        ),
    ),
    "n1": RobotSpec(
        robot_id="n1",
        display_name="N1",
        manufacturer="Fourier Intelligence",
        model_relpath="robots/fourier/n1/n1.xml",
        scene_relpath="scenes/n1.xml",
        license_spdx="Apache-2.0",
        license_relpath="robots/fourier/LICENSE",
        source_repository=_MUJOCO_MENAGERIE_REPOSITORY,
        source_revision=_MUJOCO_MENAGERIE_REVISION,
        source_manifest_relpath="robots/fourier/SOURCE.yaml",
        model_sha256="c2bb60e28af4322871db354ab8732f514ca83f0a632f9ee12bf05a032e1fb981",
        expected_nq=30,
        expected_nv=29,
        expected_nu=23,
        required_bodies=(
            "base_link",
            "left_thigh_roll_link",
            "left_shank_pitch_link",
            "left_foot_roll_link",
            "left_foot_pitch_link",
            "left_toe_link",
            "right_thigh_roll_link",
            "right_shank_pitch_link",
            "right_foot_roll_link",
            "right_foot_pitch_link",
            "right_toe_link",
            "torso_link",
            "left_end_effector_link",
            "right_end_effector_link",
        ),
        required_joints=(
            "base_free_joint",
            "left_hip_pitch_joint",
            "left_knee_pitch_joint",
            "left_ankle_pitch_joint",
            "right_hip_pitch_joint",
            "right_knee_pitch_joint",
            "right_ankle_pitch_joint",
        ),
    ),
    "adam": RobotSpec(
        robot_id="adam",
        display_name="ADAM Lite",
        manufacturer="PNDbotics",
        model_relpath="robots/pndbotics/adam/adam_lite.xml",
        scene_relpath="scenes/adam.xml",
        license_spdx="MIT",
        license_relpath="robots/pndbotics/LICENSE",
        source_repository=_MUJOCO_MENAGERIE_REPOSITORY,
        source_revision=_MUJOCO_MENAGERIE_REVISION,
        source_manifest_relpath="robots/pndbotics/SOURCE.yaml",
        model_sha256="8dbbaa02fb0da56cfab508d7c0a303d565c7a35db79e4be8c9528dbef49f5819",
        expected_nq=32,
        expected_nv=31,
        expected_nu=25,
        required_bodies=(
            "pelvis",
            "left_hip_roll_link_aux",
            "left_knee_link_aux",
            "left_ankle_link_aux",
            "toeLeft",
            "left_toe_link",
            "right_hip_roll_link_aux",
            "right_knee_link_aux",
            "right_ankle_link_aux",
            "toeRight",
            "right_toe_link",
            "torso",
            "left_hand_link",
            "right_hand_link",
        ),
        required_joints=(
            "floating_joint",
            "hipPitch_Left",
            "kneePitch_Left",
            "anklePitch_Left",
            "hipPitch_Right",
            "kneePitch_Right",
            "anklePitch_Right",
        ),
    ),
    "t1": RobotSpec(
        robot_id="t1",
        display_name="T1",
        manufacturer="Booster Robotics",
        model_relpath="robots/booster/t1/t1.xml",
        scene_relpath="scenes/t1.xml",
        license_spdx="Apache-2.0",
        license_relpath="robots/booster/LICENSE",
        source_repository=_MUJOCO_MENAGERIE_REPOSITORY,
        source_revision=_MUJOCO_MENAGERIE_REVISION,
        source_manifest_relpath="robots/booster/SOURCE.yaml",
        model_sha256="d9f630545e8f8450a414f3f4e51406a731f17640cf7c9883facabbbd5f9f017d",
        expected_nq=30,
        expected_nv=29,
        expected_nu=23,
        required_bodies=(
            "Trunk",
            "Hip_Roll_Left",
            "Shank_Left",
            "Ankle_Cross_Left",
            "left_foot_link",
            "left_toe_link",
            "Hip_Roll_Right",
            "Shank_Right",
            "Ankle_Cross_Right",
            "right_foot_link",
            "right_toe_link",
            "left_hand_joi",
            "right_hand_joi",
        ),
        required_joints=(
            "Left_Hip_Pitch",
            "Left_Knee_Pitch",
            "Left_Ankle_Pitch",
            "Right_Hip_Pitch",
            "Right_Knee_Pitch",
            "Right_Ankle_Pitch",
        ),
    ),
    "pm01": RobotSpec(
        robot_id="pm01",
        display_name="PM01",
        manufacturer="ENGINEAI",
        model_relpath="robots/engineai/pm01/xml/serial_pm_v2.xml",
        scene_relpath="scenes/pm01.xml",
        license_spdx="BSD-3-Clause",
        license_relpath="robots/engineai/LICENSE",
        source_repository=_GMR_REPOSITORY,
        source_revision=_GMR_REVISION,
        source_manifest_relpath="robots/engineai/SOURCE.yaml",
        model_sha256="959c75f826e7d583e2ca70c08881f37791608711351ef792d440db1f7735e906",
        expected_nq=31,
        expected_nv=30,
        expected_nu=24,
        required_bodies=(
            "LINK_BASE",
            "LINK_HIP_ROLL_L_AUX",
            "LINK_KNEE_PITCH_L_AUX",
            "LINK_ANKLE_PITCH_L_AUX",
            "LINK_FOOT_L",
            "LINK_TOE_L",
            "LINK_HIP_ROLL_R_AUX",
            "LINK_KNEE_PITCH_R_AUX",
            "LINK_ANKLE_PITCH_R_AUX",
            "LINK_FOOT_R",
            "LINK_TOE_R",
            "LINK_TORSO_YAW",
            "LINK_HAND_L",
            "LINK_HAND_R",
        ),
        required_joints=(
            "J00_HIP_PITCH_L",
            "J03_KNEE_PITCH_L",
            "J04_ANKLE_PITCH_L",
            "J06_HIP_PITCH_R",
            "J09_KNEE_PITCH_R",
            "J10_ANKLE_PITCH_R",
        ),
    ),
}

ROBOTS = MappingProxyType(_ROBOTS)


def list_robots() -> tuple[RobotSpec, ...]:
    """Return supported robots in stable public order."""

    public_order = (
        "g1",
        "h1",
        "h2",
        "r1",
        "k1",
        "apollo",
        "oli",
        "n1",
        "adam",
        "t1",
        "pm01",
    )
    return tuple(ROBOTS[robot_id] for robot_id in public_order)


def get_robot(robot_id: str) -> RobotSpec:
    """Resolve a robot ID or raise a user-facing configuration error."""

    normalized = robot_id.strip().lower()
    try:
        return ROBOTS[normalized]
    except KeyError as exc:
        supported = ", ".join(ROBOTS)
        raise ConfigurationError(
            f"Unsupported robot {robot_id!r}. Supported robots: {supported}."
        ) from exc
