"""Stable public stage identifiers used by CLI, logs, and web UI."""

from enum import Enum


class PipelineStage(str, Enum):
    CREATED = "CREATED"
    VALIDATING = "VALIDATING"
    LOADING_MODEL = "LOADING_MODEL"
    DMR = "DMR"
    INITIAL_COLLISION = "INITIAL_COLLISION"
    EXTRACTING_TRAJECTORIES = "EXTRACTING_TRAJECTORIES"
    ARA = "ARA"
    FPA_TARGETS = "FPA_TARGETS"
    FPA_IK = "FPA_IK"
    GROUNDING = "GROUNDING"
    FINAL_COLLISION = "FINAL_COLLISION"
    VALIDATING_OUTPUT = "VALIDATING_OUTPUT"
    EXPORTING = "EXPORTING"
    RENDERING = "RENDERING"
    SUCCEEDED = "SUCCEEDED"
    SUCCEEDED_WITH_WARNINGS = "SUCCEEDED_WITH_WARNINGS"
    CANCEL_REQUESTED = "CANCEL_REQUESTED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"
